conditional workflow added

diff --git a/.github/workflows/conditional.yml b/.github/workflows/conditional.yml
--- a/.github/workflows/conditional.yml
+++ b/.github/workflows/conditional.yml
@@ -11,8 +11,10 @@ jobs:
     steps:
       - name: run if banch is main. 
         id: main-branch
-        if: github.ref_name !== 'main'
-        run: echo "job running on main branch"
+        if: github.ref_name == 'main'
+        run: |
+          echo "Simulating a failure on main branch..."
+          exit 1
 
       - name: run on last step failure
         if: failure() && steps.main-branch.outcome == 'failure'
