conditional workflow added

diff --git a/.github/workflows/conditional.yml b/.github/workflows/conditional.yml
--- a/.github/workflows/conditional.yml
+++ b/.github/workflows/conditional.yml
@@ -9,12 +9,13 @@ jobs:
   conditional-workflow:
     runs-on: ubuntu-latest
     steps:
-    #  - name: run if banch is main. 
-     #   id: main-branch
-      #  if: github.ref_name == 'main'
-       # run: |
-        #  echo "Simulating a failure on main branch..."
-         # exit
+      - name: run if banch is main. 
+        id: main-branch
+        if: github.ref_name == 'main'
+        run: |
+          echo "Simulating a failure on main branch..."
+          exit 1
+        continue-on-error: true
 
       - name: run on last step failure
         if: failure() && steps.main-branch.outcome == 'failure'
