Fail-fast

diff --git a/.github/workflows/matrix.yml b/.github/workflows/matrix.yml
--- a/.github/workflows/matrix.yml
+++ b/.github/workflows/matrix.yml
@@ -10,13 +10,17 @@ jobs:
   matrix-strategy:
     runs-on: ${{matrix.os}}
     strategy:
+      
+      fail-fast: true
+
+
       matrix:
         python-version: ["3.10", "3.12", "3.14"]
         os: [ubuntu-latest, windows-latest]
       
-        exclude:
-          - python-version: 3.14
-          - os: windows-latest  
+      # exclude:
+        # - python-version: 3.14
+        # - os: windows-latest  
 
 
     steps: 
@@ -28,4 +32,12 @@ jobs:
         with:
           python-version: ${{matrix.python-version}}
       - name: print python version
-        run: python --version  
+        run: python --version
+
+      - name: Trigger failure on Python 3.12
+        if: matrix.python-version == '3.12'
+        run: |
+          echo "Simulating a failure on experimental version..."
+          exit 1
+
+  
